## Crear un vector de ceros de tamaño 10

In [3]:
import numpy as np
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [4]:
vector = np.zeros(10)
vector[5]=1
print(vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc

In [6]:
vector = np.arange(50)
aux=vector[0]
aux2=vector[-1]
vector[-1]=aux
vector[0]=aux2
print(vector)

[49  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48  0]


## Crear una matriz de 3 x 3 con valores del cero al 8

In [9]:
vector = np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Encontrar los indices que no sean cero en un arreglo

In [14]:
import numpy as np
arreglo = [1,2,0,0,4,0]
arreglo_n = np.array([1,2,0,0,4,0])
indices_arreglo_no_cero = arreglo_n > 0
print(arreglo_n[indices_arreglo_no_cero])

[1 2 4]


## Crear una matriz de identidad 3 x 3 

In [17]:
matriz = np.eye(3)
print(matriz)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Crear una matriz 3 x 3 x 3 con valores randomicos

In [24]:
matriz = np.random.rand(3,3,3)
print(matriz)

[[[0.71841238 0.6867064  0.58858865]
  [0.3736167  0.77645038 0.07940413]
  [0.46531386 0.66861176 0.13249637]]

 [[0.85675386 0.98574113 0.77994598]
  [0.22140529 0.78280038 0.51387706]
  [0.36631051 0.23445799 0.70863656]]

 [[0.74774425 0.04706732 0.98164184]
  [0.20144488 0.91214353 0.0274571 ]
  [0.68585269 0.76855559 0.0695637 ]]]


## Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [35]:
matriz = np.arange(100).reshape(10,10)
print("Mayor valor ",matriz.max())
print("Menor valor ",matriz.min())

Mayor valor  99
Menor valor  0


## Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [40]:
from scipy import misc
mapache = misc.face()
unicos_elementos = np.unique(mapache)
print(unicos_elementos.size)

256


## ¿Como crear una serie de una lista, diccionario o arreglo?

In [41]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [43]:
import pandas as pd 
serie_lista = pd.Series(mylist)
print(serie_lista)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [44]:
serie_dict = pd.Series(mydict)
print(serie_dict)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [45]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 

In [55]:
datos =pd.DataFrame()
datos.append(ser,ignore_index=True)

a    b    c    d    e    f    g    h    i    j  ...      q     r     s  \
0  0.0  1.0  2.0  4.0  3.0  5.0  6.0  7.0  8.0  9.0  ...   16.0  17.0  18.0   

      t     u     v     w     x     y     z  
0  19.0  20.0  21.0  22.0  23.0  24.0  25.0  

[1 rows x 26 columns]

## ¿Como combinar varias series para hacer un DataFrame?

In [65]:
import numpy as np
datos =pd.DataFrame()
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
datos=datos.append(ser1,ignore_index=True)
datos=datos.append(ser2,ignore_index=True)
print(datos)

  0  1  2  3  4  5  6  7  8  9  ...  16  17  18  19  20  21  22  23  24  25
0  a  b  c  e  d  f  g  h  i  j ...   q   r   s   t   u   v   w   x   y   z
1  0  1  2  3  4  5  6  7  8  9 ...  16  17  18  19  20  21  22  23  24  25

[2 rows x 26 columns]


## ¿Como obtener los items que esten en una serie A y no en una serie B?

In [66]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [108]:
indices= ser1.isin(ser2)
ser1[np.invert(indices)]

0    1
1    2
2    3
dtype: int64

## ¿Como obtener los items que no son comunes en una serie A y serie B?

In [88]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [109]:
indices= ser1.isin(ser2)
ser1[np.invert(indices)]
indices2= ser2.isin(ser1)
ser2[np.invert(indices2)]
print(ser1[np.invert(indices)],ser2[np.invert(indices2)])

0    1
1    2
2    3
dtype: int64 2    6
3    7
4    8
dtype: int64


1    5
2    6
3    7
4    8
dtype: int64

## ¿Como obtener el numero de veces que se repite un valor en una serie?

In [110]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [112]:
ser.value_counts()

a    5
c    5
g    4
e    4
h    4
d    4
f    3
b    1
dtype: int64

## ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [113]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [117]:
ser.fillna(0)

0     1
1     4
2     1
3     4
4     3
5     4
6     4
7     2
8     3
9     1
10    2
11    4
dtype: int32

## ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

In [123]:
ser = pd.Series(np.random.randint(1, 10, 35))
datos = pd.DataFrame()
datos.append(ser,ignore_index=True)

0    1    2    3    4    5    6    7    8    9  ...    25   26   27   28  \
0  6.0  9.0  5.0  7.0  1.0  4.0  5.0  7.0  8.0  3.0 ...   7.0  8.0  5.0  9.0   

    29   30   31   32   33   34  
0  8.0  4.0  2.0  9.0  3.0  7.0  

[1 rows x 35 columns]

In [119]:
ser

0     1
1     4
2     4
3     6
4     3
5     1
6     3
7     2
8     8
9     8
10    9
11    3
12    7
13    3
14    3
15    5
16    5
17    2
18    4
19    4
20    3
21    4
22    6
23    4
24    2
25    7
26    4
27    7
28    2
29    9
30    5
31    3
32    7
33    8
34    1
dtype: int32

## ¿Obtener los valores de una serie conociendo la posicion por indice?

In [124]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [125]:
ser.iloc[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

## ¿Como anadir series vertical u horizontalmente a un DataFrame?


In [126]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [127]:
# horizontalmente
datos = pd.DataFrame()

In [133]:
datos.append(ser1,ignore_index=True)

0    1    2    3    4
0  0.0  1.0  2.0  3.0  4.0

## ¿Obtener la media de una serie agrupada por otra serie?

In [134]:
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'zanahoria', 'manzana', 'manzana', 'banana', 'manzana', 'banana', 'manzana', 'zanahoria', 'manzana']


## ¿Como importar solo columnas especificas de un archivo csv?

In [137]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
datos = pd.read_csv(url)
columnas = ["crim","zn","indus","chas","nox","rm",]

In [ ]:
datos = datos[columnas]